# Generated by Django 4.2.6 on 2023-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_color_person_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='color',
        ),
        migrations.AddField(
            model_name='person',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='home.color'),
        ),
    ]
